name: Rule benchmark check

on:
  pull_request:
    branches: [main]
    paths: ["rules/*.go"]

jobs:
  benchmark:
    permissions:
      contents: read # access to check out code and install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Benchmark
      run: go test -bench=. -benchtime=10s -count=10 > benchmark.out

    - name: Get workflow run ID for latest benchmark on main
      id: get_run_id
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
      run: |
        run_id=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --jq '.artifacts[0].workflow_run.id' \
          "/repos/ONordander/pgcheck/actions/artifacts?name=benchmark.main.out")
        echo "run_id=${run_id}" >> "$GITHUB_OUTPUT"

    - name: Download previous benchmark
      uses: actions/download-artifact@v4
      with:
        name: benchmark.main.out
        path: ./benchmark-main/
        run-id: ${{ steps.get_run_id.outputs.run_id }}
        github-token: ${{ secrets.GHTOKEN }}

    - name: Compare benchmark
      shell: bash
      run: |
        diff=$(go tool benchstat --format=csv ./benchmark-main/benchmark.out benchmark.out | tail -1 | cut -d ',' -f 6 | sed -E "s/\%//g")
        if [[ "$?" != "0" ]]; then
          exit 1;
        fi

        echo "Benchmark diff to main: ${diff}%"
        result=$(echo "$diff" | awk '{print " 0" $1 " > 5.0"}' | bc)
        if [[ "$result" == "1" ]]; then
          echo "::error::Benchmark increased by more than 5 percent"
          echo "benchmark.out:"
          cat benchmark.out
          exit 1
        fi
